import { Router } from "express";
import authrouter from "./features/auth/controller";
import inventoryRouter from "./features/resource/Inventory/inventoryRoutes";
import appointmentRouter from "./features/resource/appointment/AppointmentRoutes";
import todoRouter from "./features/todos/todoRoute";
import hrRouter from "./features/resource/HRMS/hrRoutes"
import equipmentsRouter from "./features/equipments/equipmentsRouter";
import ipdRouter from "./features/ipd/ipdRoute";
import invoiceRouter from "./features/account/invoices/invoiceRouter";
import surgeryRouter from "./features/surgery/surgeryRoutes";
import dataRouter from "./features/data_fetchers/controller";
import patientInfoRouter from "./features/account/patients/patientRoutes";
import accountRouter from "./features/account/AccountRoutes";
import financeRouter from "./features/finance/financeRouter";
import emergencyAlertRouter from "./features/resource/emergencyAlert/emergencyAlertRoute";
import emergencyRouter from "./features/emergency/emergencyRoutes";
import doctorRouter from "./features/account/doctors/doctorRoutes";
import passkeyRouter from "./features/auth/createPasskeyRouter";
import chatRouter from "./features/chats/chatRouter";
import pricingRouter from "./features/account/invoices/CGHSListMVC";
import prescriptionRouter from "./features/prescription/prescriptionRoute";
import formRouter from "./features/forms/formsRouter";
import formDataRouter from "./features/formData/formDataRoute";
import sampleRouter from "./features/LabsScansTest/diagnostic/sampleCollection/sampleRoutes";
import paymentRouter from "./utils/Razorpay/razorpay";
import diagnosticRouter from "./features/LabsScansTest/diagnostic/LabsScansTestRouter";
import notificationRouter from "./features/LabsScansTest/labScansNotification/investigationRouter";
import orderNotificationRouter from "./features/LabsScansTest/orderNotification/orderNotificationRouter";
import uploadRouter from "./features/upload/uploadRouter";
import vmsRouter from "./features/equipments/vendorManagement/vmsRoutes";
import radiologyRouter from "./features/LabsScansTest/radiology/radiologyRouter";
const ApiRouter = Router();
ApiRouter.use("/chats", chatRouter);
ApiRouter.use("/auth", authrouter);
ApiRouter.use("/Accounts", accountRouter);
ApiRouter.use("/doctor", doctorRouter);
ApiRouter.use("/invoice", invoiceRouter);
ApiRouter.use("/patient", patientInfoRouter);
ApiRouter.use("/equipment", equipmentsRouter);
ApiRouter.use("/emergency", emergencyRouter);
ApiRouter.use("/finance", financeRouter);
ApiRouter.use("/ipd", ipdRouter);
ApiRouter.use("/appointment", appointmentRouter);
ApiRouter.use("/alert", emergencyAlertRouter);
ApiRouter.use("/hr", hrRouter);
ApiRouter.use("/inventory", inventoryRouter);
ApiRouter.use("/surgery", surgeryRouter);
ApiRouter.use("/data", dataRouter);
ApiRouter.use("/todo", todoRouter);
ApiRouter.use("/passkey", passkeyRouter);
ApiRouter.use("/pricing", pricingRouter);
ApiRouter.use("/prescription", prescriptionRouter);
ApiRouter.use("/forms", formRouter);
ApiRouter.use("/formData", formDataRouter);
ApiRouter.use("/sample", sampleRouter);
ApiRouter.use("/payment", paymentRouter);
ApiRouter.use("/labsTests", diagnosticRouter);
ApiRouter.use("/notification", notificationRouter);
ApiRouter.use("/orderNotification", orderNotificationRouter);
ApiRouter.use("/upload", uploadRouter);
ApiRouter.use("/vms", vmsRouter);
ApiRouter.use("/radiology", radiologyRouter);
export default ApiRouter;